version: '3.8'

services:
  ai-recruiter:
    build: .
    container_name: ai-resume-matcher
    ports:
      - "8501:8501"
    volumes:
      # Монтируем папку с моделью, чтобы не терять дообученную модель
      - ./my_hr_model:/app/my_hr_model
      # Монтируем исходники для разработки (изменения сразу видны)
      - ./app.py:/app/app.py
      - ./utils.py:/app/utils.py
      - ./train_data.json:/app/train_data.json
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped